Description: >
  UdaPeople backend stack.

Parameters:
  ID:
    Description: Unique identifier.
    Type: String

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      SecurityGroupIds:
        - sg-0a9c371825823cffb
      KeyName: aws-test-key 
      ImageId: ami-052efd3df9dad4825
      Tags:
        - Key: Name
          Value: !Sub backend-${ID}
