version: 2.1

commands:
   destroy-environment:
     steps:
       - run:
           name: Destroy environment
           when: on_fail
           command: |
             aws cloudformation delete-stack --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}
jobs:
#tests
   build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm install
            npm run build

   build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Build back-end
          command: |
            cd backend
            npm install
            npm run build         

   test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Testing Frontend
          command: |
            cd frontend
            npm install
            npm run test 

   test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Testing Backend
          command: |
            cd backend
            npm install
            npm run test  

   scan-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Scanning Frontend
          command: |
            cd frontend
            npm install
            npm audit fix --audit-level=critical --force     

   scan-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Scanning Backend
          command: |
            cd backend
            npm install
            npm audit fix --audit-level=critical --force

#deployments  
   deploy-backend-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensuring Backend Exists
          command: |
            aws cloudformation deploy \
            --template-file .circleci/files/backend.yml \
            --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
            --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
            --tags project=udapeople 
          
      - destroy-environment   

   deploy-frontend-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensuring Frontend Exists
          command: |
            aws cloudformation deploy \
            --template-file .circleci/files/frontend.yml \
            --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
            --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
            --tags project=udapeople              


workflows:
  workflow_pipeline:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires:
            [build-frontend]
      - test-backend:
          requires:
            [build-backend]
      - scan-frontend:
          requires:
            [build-frontend]
      - scan-backend:
          requires:
            [build-backend] 
      - deploy-backend-infrastructure
      - deploy-frontend-infrastructure:
          requires:
            deploy-backend-infrastructure                      